---
title: "hf"
author: "Sarah Urbut"
date: "3/14/2021"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

Here we organize the data frame for preliminary analysis.


```{r}

library("workflowr")
df=read.csv("data/ms_hf.csv")
good_df=df[,c("X","Age.of.Death","Gender","Initial.BP..SYSTOLIC","Earliest..Creatinine1")]

#names(df)
ef_min=df[,grep(names(df),pattern = "EF_Min")]

##looks like 
df_min=df[,c("EF_Min..EF","EF_Min..LVEjectionFraction2D","EF_Min..EF","EF_Min..LVEjectionFraction2D","EF_Min..LVEFModSimpBiPlane","EF_Min..EstimatedEF")]
          
mean_ef_min=apply(df_min,1,function(x){
  x=as.numeric(x)
  mean(na.omit(x))})


ef_max=df[,grep(names(df),pattern = "EF_Max")]
names(ef_max)

ef_max=df[,c("EF_Max..EF","EF_Max..LVEjectionFraction2D","EF_Max..EF","EF_Max..LVEjectionFraction2D","EF_Max..LVEFModSimpBiPlane","EF_Max..EstimatedEF")]      

mean_ef_max=apply(ef_max,1,function(x)
  {x=as.numeric(x)
  mean(na.omit(x))
  })
               


full_ef=data.frame(good_df,mean_ef_max,mean_ef_min)
head(full_ef)
write.table(full_ef,"data/full_ef.txt")
```

Here I extract and convert dates:
```{r}
library("lubridate")
ef_max_date=dmy(df[,"EF_Max.EchoDate"])
ef_min_date=dmy(df[,"EF_Min..EchoDate"])
d=ef_max_date-ef_min_date
date.positive=d>0

```
Here we divide the table into those with improved EF and no change in EF

```{r}
delta=mean_ef_max-mean_ef_min
summary(na.omit(delta))##we can see that 25% of individuals had an improvement greater than or equal to 25%
hist(delta)
full_ef=cbind(full_ef,delta,date.positive)
full_ef$Gender=as.factor(full_ef$Gender)

## indicate positive and negative date
complete_ef_data=full_ef[!is.na(full_ef$date.positive),]##only pull out the ones with two dates
complete_ef_data$date.positive[complete_ef_data$date.positive=="FALSE"]=-1
complete_ef_data$date.positive[complete_ef_data$date.positive=="TRUE"]=1

###now plot real delta

hist(complete_ef_data$delta*complete_ef_data$date.positive,main="Delta")
##This many are improving
sum(complete_ef_data$date.positive==1)
##this many are getting worse
sum(complete_ef_data$date.positive==-1)





```



As we can see, no huge apparent differences in initital creatining and BP or gender composition.


